# name: Hello World

#   on: push

# jobs:
#   hello-job:
#     runs-on: ubuntu-latest

#   steps:
#     -name: Echo Text
#      run echo "Hello World"

name: Hello World
'on': push
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: 'echo "Hello, world!"'